org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=26.2
loader_version=0.19.5
loom_version=1.17-SNAPSHOT
fabric_api_version=0.159.0+26.2
ukulib_api_version=2.1.1+26.2
bedrockify_version=1.11.7+mc26.1

mod_version=1.0.0+mc26.2
maven_group=dev.fixpot47
archives_base_name=fixpots-armor-hud
